### PR TITLE
add "always saves after" option

### LINKED ISSUE #2: Save some played worlds to mitigate damage from accidental resets
a way to implement it would be to save the world if it has been played for more than X minutes (igt?)

### PR DESCRIPTION
**Pull request by tildejustin**
changes:
- removes the fast reset button and atum hotkey behavior of fastresetting after a configurable amount of server ticks has passed

resolves #2

### CODE REVIEW

**Comment by contariaa** [comment]
what are your thoughts on adding specific translations for round minutes, like 1 minute, 2 minutes, etc?

**Comment by tildejustin** [comment]
179 seconds - 3 minute - 181 seconds seems like it wouldn't help readability all that much, I could extend IntegerOption for an "x mins x seconds" getText maybe?

**Comment by tildejustin** [comment]
it is an internal api though, lmk your thoughts.

**Comment by tildejustin** [comment]
this should be in its own class

**Comment by contariaa** [comment]
From my initial understanding, when turning the option to 0 it would just default to the current behaviour of always showing the menu.quitWorld button, now it seems like setting it to 0 would just never show the button?

**Comment by tildejustin** [comment]
it looks like I may have broken that behavior at some point in refactoring, that was the initial use of the > 0 check..

**Review by contariaa — COMMENTED** [review]
Codewise this looks good to me, only two concerns:
1. In other mods i usually put gui related code in a `gui` package not `widget`.
2. I'm unsure if this option should be enabled by default. On one hand less unverifiable runs is obviously great, on the other a disappearing button might confuse people?

**Comment by tildejustin** [comment]
0 default is fine, I'm the target audience anyway I guess. fixed package.

**Review by contariaa — APPROVED** [review]
Lgtm!

**Pull request merged**
